version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Websocket-py"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mzxzitoup6w1"
s3_prefix = "Websocket-py"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
